# Generated by Django 6.1.2 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
